// Code generated by MockGen. DO NOT EDIT.
// Source: mailer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMailer is a mock of Mailer interface
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
}

// MockMailerMockRecorder is the mock recorder for MockMailer
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendPassword mocks base method
func (m *MockMailer) SendPassword(to, nickname, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPassword", to, nickname, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPassword indicates an expected call of SendPassword
func (mr *MockMailerMockRecorder) SendPassword(to, nickname, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPassword", reflect.TypeOf((*MockMailer)(nil).SendPassword), to, nickname, token)
}
